import { Navbar } from "@/components/landing/Navbar";
import { Footer } from "@/components/landing/Footer";
import { Link } from "react-router-dom";
import { ChevronLeft, AlertTriangle } from "lucide-react";

const TermsOfService = () => {
  return (
    <div className="min-h-screen bg-background">
      <Navbar />
      <main className="pt-24 sm:pt-28 pb-16">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-4xl">
          {/* Breadcrumb */}
          <Link 
            to="/" 
            className="inline-flex items-center text-sm text-muted-foreground hover:text-foreground transition-colors mb-8"
          >
            <ChevronLeft className="w-4 h-4 mr-1" />
            Back to Home
          </Link>

          {/* Header */}
          <div className="mb-8">
            <h1 className="font-display text-3xl sm:text-4xl lg:text-5xl text-foreground mb-4">
              Terms of Service
            </h1>
            <p className="text-muted-foreground">
              Last updated: January 25, 2026
            </p>
          </div>

          {/* Important Notice Box */}
          <div className="bg-destructive/10 border border-destructive/20 rounded-lg p-6 mb-10">
            <div className="flex items-start gap-4">
              <AlertTriangle className="w-8 h-8 text-destructive flex-shrink-0 mt-1" />
              <div>
                <h2 className="font-display text-xl text-foreground mb-2">
                  Important: Please Read Carefully
                </h2>
                <p className="text-muted-foreground">
                  These Terms of Service contain important provisions regarding liability limitations and assumption of risk. By using MatSide, you acknowledge that you have read, understood, and agree to be bound by these terms.
                </p>
              </div>
            </div>
          </div>

          {/* Content Sections */}
          <div className="prose prose-lg max-w-none">
            <section className="mb-10">
              <h2 className="font-display text-2xl text-foreground mb-4 border-b border-border pb-2">
                1. Acceptance of Terms
              </h2>
              <p className="text-muted-foreground">
                By accessing or using MatSide ("the Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, you may not use the Service. These Terms apply to all users, including Team Administrators, League Organizers, and any other individuals who access or use the Service.
              </p>
            </section>

            <section className="mb-10">
              <h2 className="font-display text-2xl text-foreground mb-4 border-b border-border pb-2">
                2. Description of Service
              </h2>
              <p className="text-muted-foreground">
                MatSide is a software platform designed to assist wrestling teams and leagues with roster management, meet coordination, and automated match pairing. The Service provides tools to streamline administrative tasks associated with youth wrestling events.
              </p>
            </section>

            <section className="mb-10">
              <h2 className="font-display text-2xl text-foreground mb-4 border-b border-border pb-2">
                3. Advisory Nature of Services
              </h2>
              <div className="bg-muted border border-border rounded-lg p-6">
                <p className="text-foreground font-medium mb-4 text-lg">
                  IMPORTANT DISCLAIMER
                </p>
                <p className="text-muted-foreground mb-4">
                  MatSide provides automated matchmaking suggestions based on user-provided input data, including but not limited to athlete age, weight, experience level, and skill ratings. These suggestions are generated by algorithms designed for administrative convenience only.
                </p>
                <p className="text-foreground font-semibold">
                  YOU ACKNOWLEDGE THAT YOU ARE SOLELY RESPONSIBLE FOR REVIEWING AND APPROVING ALL MATCHUPS FOR SAFETY.
                </p>
                <p className="text-muted-foreground mt-4">
                  MatSide's matchmaking suggestions do not constitute professional safety advice. All match pairings must be reviewed and approved by qualified personnel (coaches, referees, or other officials) who are present at the event and can assess the athletes' physical condition, readiness, and suitability for competition.
                </p>
              </div>
            </section>

            <section className="mb-10">
              <h2 className="font-display text-2xl text-foreground mb-4 border-b border-border pb-2">
                4. Assumption of Risk
              </h2>
              <div className="bg-muted border border-border rounded-lg p-6">
                <p className="text-foreground font-medium mb-4 text-lg">
                  INHERENT RISKS OF WRESTLING
                </p>
                <p className="text-muted-foreground mb-4">
                  Wrestling is a contact sport that involves inherent risks of physical injury, including but not limited to sprains, strains, fractures, concussions, and other bodily harm. These risks exist regardless of the precautions taken or the quality of match pairings.
                </p>
                <p className="text-foreground font-semibold mb-4">
                  MatSide is a software provider, not a safety official, coach, referee, or medical professional.
                </p>
                <p className="text-muted-foreground">
                  By using the Service to facilitate wrestling events, you acknowledge and assume all risks associated with athlete participation in wrestling activities. You agree that MatSide bears no responsibility for injuries sustained during wrestling competitions or practices, regardless of how matches were arranged or suggested.
                </p>
              </div>
            </section>

            <section className="mb-10">
              <h2 className="font-display text-2xl text-foreground mb-4 border-b border-border pb-2">
                5. User Responsibility for Data Accuracy
              </h2>
              <div className="bg-muted border border-border rounded-lg p-6">
                <p className="text-foreground font-medium mb-4 text-lg">
                  ACCURACY OF ATHLETE INFORMATION
                </p>
                <p className="text-muted-foreground mb-4">
                  The quality and safety of match pairings generated by MatSide depend entirely on the accuracy of the data entered by users. Users are solely responsible for ensuring that all athlete information—including but not limited to dates of birth, weights, experience levels, and skill ratings—is accurate and current.
                </p>
                <p className="text-foreground font-semibold mb-4">
                  MatSide is not liable for unsafe pairings resulting from incorrect, outdated, or falsified athlete data entered by users.
                </p>
                <p className="text-muted-foreground">
                  This includes, without limitation:
                </p>
                <ul className="list-disc list-inside text-muted-foreground space-y-2 ml-4 mt-3">
                  <li>Incorrect birthdates that misrepresent an athlete's age</li>
                  <li>Inaccurate weight measurements</li>
                  <li>Misrepresented experience or skill levels</li>
                  <li>Failure to update information after changes occur</li>
                  <li>Intentional falsification of any athlete data</li>
                </ul>
              </div>
            </section>

            <section className="mb-10">
              <h2 className="font-display text-2xl text-foreground mb-4 border-b border-border pb-2">
                6. Limitation of Liability
              </h2>
              <div className="bg-muted border border-border rounded-lg p-6">
                <p className="text-foreground font-medium mb-4 text-lg">
                  LIMITATION ON DAMAGES
                </p>
                <p className="text-muted-foreground mb-4">
                  TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL MATSIDE, ITS OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, OR AFFILIATES BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA, OR OTHER INTANGIBLE LOSSES, ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF THE SERVICE.
                </p>
                <p className="text-foreground font-semibold">
                  IN ANY EVENT, MATSIDE'S TOTAL AGGREGATE LIABILITY TO YOU FOR ALL CLAIMS ARISING OUT OF OR RELATING TO THE USE OF THE SERVICE SHALL NOT EXCEED THE AMOUNT PAID BY YOU TO MATSIDE FOR THE SERVICE DURING THE TWELVE (12) MONTHS IMMEDIATELY PRECEDING THE EVENT GIVING RISE TO THE CLAIM.
                </p>
              </div>
            </section>

            <section className="mb-10">
              <h2 className="font-display text-2xl text-foreground mb-4 border-b border-border pb-2">
                7. Indemnification
              </h2>
              <p className="text-muted-foreground">
                You agree to indemnify, defend, and hold harmless MatSide and its officers, directors, employees, agents, and affiliates from and against any and all claims, liabilities, damages, losses, costs, and expenses (including reasonable attorneys' fees) arising out of or in any way connected with:
              </p>
              <ul className="list-disc list-inside text-muted-foreground space-y-2 ml-4 mt-3">
                <li>Your use of the Service</li>
                <li>Your violation of these Terms</li>
                <li>Your violation of any rights of another party</li>
                <li>Any claim that your use of the Service caused damage to a third party</li>
                <li>Injuries sustained during wrestling events organized using the Service</li>
              </ul>
            </section>

            <section className="mb-10">
              <h2 className="font-display text-2xl text-foreground mb-4 border-b border-border pb-2">
                8. User Accounts
              </h2>
              <p className="text-muted-foreground mb-4">
                You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You agree to:
              </p>
              <ul className="list-disc list-inside text-muted-foreground space-y-2 ml-4">
                <li>Provide accurate and complete information when creating your account</li>
                <li>Promptly update your account information to keep it current</li>
                <li>Notify MatSide immediately of any unauthorized use of your account</li>
                <li>Not share your account credentials with others</li>
              </ul>
            </section>

            <section className="mb-10">
              <h2 className="font-display text-2xl text-foreground mb-4 border-b border-border pb-2">
                9. Acceptable Use
              </h2>
              <p className="text-muted-foreground mb-4">
                You agree not to use the Service to:
              </p>
              <ul className="list-disc list-inside text-muted-foreground space-y-2 ml-4">
                <li>Violate any applicable laws or regulations</li>
                <li>Enter false or misleading information about athletes</li>
                <li>Attempt to gain unauthorized access to other users' accounts or data</li>
                <li>Interfere with or disrupt the Service or servers</li>
                <li>Use the Service for any purpose other than legitimate wrestling team and league management</li>
              </ul>
            </section>

            <section className="mb-10">
              <h2 className="font-display text-2xl text-foreground mb-4 border-b border-border pb-2">
                10. Modifications to Service and Terms
              </h2>
              <p className="text-muted-foreground">
                MatSide reserves the right to modify, suspend, or discontinue the Service (or any part thereof) at any time with or without notice. We may also modify these Terms from time to time. If we make material changes, we will notify you by email or through the Service. Your continued use of the Service after such modifications constitutes your acceptance of the updated Terms.
              </p>
            </section>

            <section className="mb-10">
              <h2 className="font-display text-2xl text-foreground mb-4 border-b border-border pb-2">
                11. Termination
              </h2>
              <p className="text-muted-foreground">
                MatSide may terminate or suspend your account and access to the Service at any time, with or without cause, with or without notice. Upon termination, your right to use the Service will immediately cease. All provisions of these Terms that by their nature should survive termination shall survive, including ownership provisions, warranty disclaimers, indemnification, and limitations of liability.
              </p>
            </section>

            <section className="mb-10">
              <h2 className="font-display text-2xl text-foreground mb-4 border-b border-border pb-2">
                12. Governing Law
              </h2>
              <p className="text-muted-foreground">
                These Terms shall be governed by and construed in accordance with the laws of the State of Delaware, without regard to its conflict of law provisions. Any disputes arising under these Terms shall be resolved exclusively in the state or federal courts located in Delaware.
              </p>
            </section>

            <section className="mb-10">
              <h2 className="font-display text-2xl text-foreground mb-4 border-b border-border pb-2">
                13. Contact Information
              </h2>
              <p className="text-muted-foreground">
                If you have any questions about these Terms of Service, please contact us at:
              </p>
              <p className="text-foreground mt-3">
                <strong>Email:</strong> <a href="mailto:hello@matsideapp.com" className="text-primary hover:underline">hello@matsideapp.com</a>
              </p>
            </section>
          </div>

          {/* Related Links */}
          <div className="mt-12 pt-8 border-t border-border">
            <p className="text-muted-foreground mb-4">Related Documents:</p>
            <Link 
              to="/privacy" 
              className="text-primary hover:underline font-medium"
            >
              Privacy Policy →
            </Link>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default TermsOfService;
